draw_text_transformed(800, 50, "Credits", 2, 2, 1)
draw_text(530, 150, "Background Music: Swngyill's Retro Music Pack - Vol. 001 By: Swngyill YOON")
draw_text(530, 200, "Recycling Bins Base Image By: S, Tim. Sprites created using Pixel It")
draw_text(530, 250, "Conveyor Belt Sprites Artwork By: Chromaeleon")
draw_text(680, 400, "Press Backspace to return to title screen")
